/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PodsAllImport } from './routes/pods/all'
import { Route as PodsPodIdImport } from './routes/pods/$podId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SettingsIndexLazyImport = createFileRoute('/settings/')()
const CreateIndexLazyImport = createFileRoute('/create/')()
const CreateListingLazyImport = createFileRoute('/create/listing')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SettingsIndexLazyRoute = SettingsIndexLazyImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/index.lazy').then((d) => d.Route),
)

const CreateIndexLazyRoute = CreateIndexLazyImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create/index.lazy').then((d) => d.Route))

const CreateListingLazyRoute = CreateListingLazyImport.update({
  id: '/create/listing',
  path: '/create/listing',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create/listing.lazy').then((d) => d.Route),
)

const PodsAllRoute = PodsAllImport.update({
  id: '/pods/all',
  path: '/pods/all',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pods/all.lazy').then((d) => d.Route))

const PodsPodIdRoute = PodsPodIdImport.update({
  id: '/pods/$podId',
  path: '/pods/$podId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pods/$podId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pods/$podId': {
      id: '/pods/$podId'
      path: '/pods/$podId'
      fullPath: '/pods/$podId'
      preLoaderRoute: typeof PodsPodIdImport
      parentRoute: typeof rootRoute
    }
    '/pods/all': {
      id: '/pods/all'
      path: '/pods/all'
      fullPath: '/pods/all'
      preLoaderRoute: typeof PodsAllImport
      parentRoute: typeof rootRoute
    }
    '/create/listing': {
      id: '/create/listing'
      path: '/create/listing'
      fullPath: '/create/listing'
      preLoaderRoute: typeof CreateListingLazyImport
      parentRoute: typeof rootRoute
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/pods/$podId': typeof PodsPodIdRoute
  '/pods/all': typeof PodsAllRoute
  '/create/listing': typeof CreateListingLazyRoute
  '/create': typeof CreateIndexLazyRoute
  '/settings': typeof SettingsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/pods/$podId': typeof PodsPodIdRoute
  '/pods/all': typeof PodsAllRoute
  '/create/listing': typeof CreateListingLazyRoute
  '/create': typeof CreateIndexLazyRoute
  '/settings': typeof SettingsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/pods/$podId': typeof PodsPodIdRoute
  '/pods/all': typeof PodsAllRoute
  '/create/listing': typeof CreateListingLazyRoute
  '/create/': typeof CreateIndexLazyRoute
  '/settings/': typeof SettingsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pods/$podId'
    | '/pods/all'
    | '/create/listing'
    | '/create'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pods/$podId'
    | '/pods/all'
    | '/create/listing'
    | '/create'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/pods/$podId'
    | '/pods/all'
    | '/create/listing'
    | '/create/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PodsPodIdRoute: typeof PodsPodIdRoute
  PodsAllRoute: typeof PodsAllRoute
  CreateListingLazyRoute: typeof CreateListingLazyRoute
  CreateIndexLazyRoute: typeof CreateIndexLazyRoute
  SettingsIndexLazyRoute: typeof SettingsIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PodsPodIdRoute: PodsPodIdRoute,
  PodsAllRoute: PodsAllRoute,
  CreateListingLazyRoute: CreateListingLazyRoute,
  CreateIndexLazyRoute: CreateIndexLazyRoute,
  SettingsIndexLazyRoute: SettingsIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pods/$podId",
        "/pods/all",
        "/create/listing",
        "/create/",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/pods/$podId": {
      "filePath": "pods/$podId.tsx"
    },
    "/pods/all": {
      "filePath": "pods/all.tsx"
    },
    "/create/listing": {
      "filePath": "create/listing.lazy.tsx"
    },
    "/create/": {
      "filePath": "create/index.lazy.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
